# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindNearestPetrolsV2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindNearestPetrolsV2
   pod ‘Alamofire’
   pod 'ObjectMapper'
   pod ‘AlamofireObjectMapper’
   pod 'Kingfisher', '~> 3.0'
   pod 'SwiftyJSON', '~> 3.1.4'
   pod 'GoogleMaps'
end
